name: Crawl All Repos

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00执行一次

jobs:
  crawl-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Crawl Repositories
        run: |
          python crawl_repos.py  # 你需要编写一个脚本来实际执行抓取操作
